name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-mysql

      - name: Deploy code
        run: |
          ssh chanuka@68.219.216.161 "cd /var/www/html/GenUML && git pull"
